// Regenerates src/environments/env-config.ts from the committed defaults,
// overriding API_BASE_URL and META_OAUTH_ENABLED from process.env when set.
// Run via the prebuild/prestart npm hooks. The generated file is gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const envDir = join(here, '..', 'src', 'environments');
const defaults = readFileSync(join(envDir, 'env-config.default.ts'), 'utf8');

const strDefault = (name) => {
  const m = defaults.match(new RegExp(`${name}\\s*=\\s*'([^']*)'`));
  if (!m) throw new Error(`apply-env: default for ${name} not found`);
  return m[1];
};
const defApiBase = strDefault('API_BASE_URL');
const defMetaAppId = strDefault('META_APP_ID');
const defOauth = /META_OAUTH_ENABLED\s*=\s*true/.test(defaults);

const apiBase = process.env.API_BASE_URL ?? defApiBase;
const metaAppId = defMetaAppId; // public constant, never env-overridden
const oauth = process.env.META_OAUTH_ENABLED != null
  ? process.env.META_OAUTH_ENABLED === 'true'
  : defOauth;

const out = `// GENERATED by scripts/apply-env.mjs — DO NOT EDIT, DO NOT COMMIT.
export const API_BASE_URL = '${apiBase}';
export const META_APP_ID = '${metaAppId}';
export const META_OAUTH_ENABLED = ${oauth};
`;
writeFileSync(join(envDir, 'env-config.ts'), out);
console.log(`[apply-env] API_BASE_URL=${apiBase} META_OAUTH_ENABLED=${oauth}`);
