"""initial ai_layer schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-07 02:54:34.254715
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS ai_layer")
    op.create_table('accounts',
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brand_id', 'platform', 'account_id'),
    schema='ai_layer'
    )
    op.create_table('brands',
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('meta_account_id', sa.Text(), nullable=True),
    sa.Column('google_customer_id', sa.Text(), nullable=True),
    sa.Column('shopify_domain', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brand_id'),
    schema='ai_layer'
    )
    op.create_table('cost_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('op', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Double(), nullable=False),
    sa.Column('priced', sa.Text(), nullable=False),
    sa.Column('cache_discount_usd', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_layer'
    )
    op.create_index('ix_cost_brand_created', 'cost_ledger', ['brand_id', 'created_at'], unique=False, schema='ai_layer')
    op.create_table('facts',
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.Text(), nullable=False),
    sa.Column('spend', sa.Double(), nullable=False),
    sa.Column('impressions', sa.Double(), nullable=False),
    sa.Column('reach', sa.Double(), nullable=False),
    sa.Column('frequency', sa.Double(), nullable=False),
    sa.Column('clicks', sa.Double(), nullable=False),
    sa.Column('ctr', sa.Double(), nullable=False),
    sa.Column('cpc', sa.Double(), nullable=False),
    sa.Column('link_clicks', sa.Double(), nullable=False),
    sa.Column('link_ctr', sa.Double(), nullable=False),
    sa.Column('cost_per_link_click', sa.Double(), nullable=False),
    sa.Column('cpm', sa.Double(), nullable=False),
    sa.Column('add_to_cart', sa.Double(), nullable=False),
    sa.Column('checkout', sa.Double(), nullable=False),
    sa.Column('purchases', sa.Double(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.Column('roas', sa.Double(), nullable=False),
    sa.Column('cpa', sa.Double(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('brand_id', 'platform', 'account_id', 'campaign_id', 'date'),
    schema='ai_layer'
    )
    op.create_index('ix_facts_brand_date', 'facts', ['brand_id', 'date'], unique=False, schema='ai_layer')
    op.create_table('brand_config',
    sa.Column('brand_id', sa.Text(), nullable=False),
    sa.Column('brand_kit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['ai_layer.brands.brand_id'], ),
    sa.PrimaryKeyConstraint('brand_id'),
    schema='ai_layer'
    )
    op.create_table('creative_jobs',
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('brand_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_kit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winners_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ledger_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_usd', sa.Double(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['ai_layer.brands.brand_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    schema='ai_layer'
    )
    op.create_index('ix_jobs_brand_created', 'creative_jobs', ['brand_id', 'created_at'], unique=False, schema='ai_layer')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS ai_layer CASCADE")
