import 'dotenv/config';

export const config = {
  port: parseInt(process.env.PORT || '3000', 10),
  jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-me',
  metaAppId: process.env.META_APP_ID || '675224542133938',
  metaAppSecret: process.env.META_APP_SECRET || '',
  tokenEncryptionKey: process.env.TOKEN_ENCRYPTION_KEY || 'dev-encryption-key-change-me-now!',
  databasePath: process.env.DATABASE_PATH || './data/cosmisk.db',
  databaseUrl: process.env.DATABASE_URL || '', // PostgreSQL connection string (production)
  nodeEnv: process.env.NODE_ENV || 'development',
  graphApiVersion: 'v22.0',
  graphApiBase: 'https://graph.facebook.com/v22.0',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  nanoBananaApiKey: process.env.NANO_BANANA_API_KEY || '',
  n8nVideoWebhook: process.env.N8N_VIDEO_WEBHOOK || '',
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || '',
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || '',
  stripePriceProMonthly: process.env.STRIPE_PRICE_PRO_MONTHLY || '',
  stripePriceProAnnual: process.env.STRIPE_PRICE_PRO_ANNUAL || '',
  stripePriceAgencyMonthly: process.env.STRIPE_PRICE_AGENCY_MONTHLY || '',
  stripePriceAgencyAnnual: process.env.STRIPE_PRICE_AGENCY_ANNUAL || '',
  appUrl: process.env.APP_URL || 'http://localhost:4200',
  googleAdsClientId: process.env.GOOGLE_ADS_CLIENT_ID || '',
  googleAdsClientSecret: process.env.GOOGLE_ADS_CLIENT_SECRET || '',
  googleAdsDeveloperToken: process.env.GOOGLE_ADS_DEVELOPER_TOKEN || '',
  googleAdsRedirectUri: process.env.GOOGLE_ADS_REDIRECT_URI || '',
  tiktokAppId: process.env.TIKTOK_APP_ID || '',
  tiktokAppSecret: process.env.TIKTOK_APP_SECRET || '',
  corsOrigins: [
    'http://localhost:4200',
    'https://cosmisk.ai',
    'https://www.cosmisk.ai',
    'https://app.cosmisk.ai',
    'https://cosmisk.vercel.app',
    process.env.FRONTEND_URL || '',
  ].filter(Boolean) as string[],
} as const;
