import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [RouterLink],
  template: `
    <!-- Page Header -->
    <section class="bg-white border-b border-gray-200 py-16 -mt-[72px] pt-[calc(4rem+72px)]">
      <div class="max-w-3xl mx-auto px-6">
        <p class="text-sm font-body text-accent font-semibold uppercase tracking-widest mb-3">Legal</p>
        <h1 class="text-4xl font-display font-bold text-navy mb-3">Terms &amp; Conditions</h1>
        <p class="text-sm text-gray-500 font-body">Last updated: 29 July 2026</p>
      </div>
    </section>

    <!-- Content -->
    <section class="bg-[#F7F8FA] py-16">
      <div class="max-w-3xl mx-auto px-6">
        <div class="bg-white rounded-2xl shadow-card border border-divider p-10 space-y-10">

          <!-- Intro -->
          <div class="space-y-4">
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              This document is an electronic record in terms of the Information Technology Act, 2000 and the rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature.
            </p>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, which require the publishing of rules and regulations, privacy policy and terms of use for access or usage of the domain name
              <a href="https://cosmisk.com" class="text-accent underline">cosmisk.com</a>
              ("Website"), including any related mobile site and mobile application (hereinafter referred to as the "Platform").
            </p>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              The Platform is owned and operated by <strong class="text-navy">Cosmisk</strong>, a sole proprietorship of <strong class="text-navy">Sanskar Saxena</strong>, registered as a Micro Enterprise under the Micro, Small and Medium Enterprises Development Act, 2006 vide Udyam Registration Number <strong class="text-navy">UDYAM-GJ-01-0663897</strong>, having its principal place of business at 27, Nirmal Bunglows, Nr Karnavati Park, Opp Baroda Expressway, CTM, Ahmedabad, Gujarat 380026, India (hereinafter referred to as "Platform Owner", "we", "us", "our").
            </p>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              Your use of the Platform and our services and tools is governed by these terms and conditions ("Terms of Use") as applicable to the Platform, including the applicable policies which are incorporated herein by reference. If you transact on the Platform, you shall be subject to the policies applicable to the Platform for such transaction. By mere use of the Platform, you shall be contracting with the Platform Owner, and these Terms of Use including the policies constitute your binding obligations with the Platform Owner.
            </p>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              These Terms of Use relate to your use of our website and services (collectively, "Services"). Any terms and conditions proposed by you which are in addition to, or which conflict with, these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use may be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
            </p>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              For the purpose of these Terms of Use, wherever the context so requires, "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user of the Platform.
            </p>
            <div class="bg-[#F7F8FA] rounded-xl border-l-4 border-accent p-5">
              <p class="text-sm font-body text-navy font-semibold leading-relaxed">
                Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use. Please read them carefully before proceeding.
              </p>
            </div>
          </div>

          <hr class="border-gray-100" />

          <!-- 1. Use of the Platform -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">1. Use of the Platform</h2>
            <div class="space-y-4">
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Neither we nor any third party provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this Website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
              </p>
              <div class="bg-[#F7F8FA] rounded-xl border border-gray-200 p-5">
                <h3 class="text-base font-semibold font-body text-navy mb-2">AI-generated output</h3>
                <p class="text-sm text-gray-600 font-body leading-relaxed">
                  The Services include analysis, recommendations and content generated using artificial intelligence. Such output is provided for informational purposes as an aid to your own judgement. It does not constitute professional, financial, legal or marketing advice, and no outcome, return on advertising spend or business result is warranted or guaranteed. All advertising, budget and creative decisions taken by you remain your sole responsibility.
                </p>
              </div>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                The contents of the Platform and the Services are proprietary to us or are licensed to us. You will not have any authority to claim any intellectual property right, title or interest in its contents, which include and are not limited to the design, layout, look and graphics. You acknowledge that unauthorised use of the Platform or the Services may lead to action against you under these Terms of Use or applicable law.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                You agree to pay us the charges associated with availing the Services, and you agree not to use the Platform or the Services for any purpose that is unlawful, illegal or forbidden by these Terms, or by Indian or local laws that might apply to you.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                You are responsible for ensuring that your use of the Services, and any data you connect to the Platform, complies with the terms of the third-party advertising platforms from which that data originates.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                You agree and acknowledge that the Website and the Services may contain links to other third-party websites. On accessing these links you will be governed by the terms of use, privacy policy and other policies of those third-party websites. These links are provided for your convenience and to provide further information.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
              </p>
            </div>
          </div>

          <hr class="border-gray-100" />

          <!-- 2. Subscriptions and Payment -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">2. Subscriptions and Payment</h2>
            <div class="space-y-4">
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Access to the Services is sold on a recurring subscription basis, billed either monthly or annually. Applicable taxes are charged in addition where required by law.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Subscriptions renew automatically at the end of each billing period unless cancelled before the renewal date. Payments are processed by a third-party payment gateway. We do not collect, store or have access to your card number, CVV, UPI PIN, net-banking password or any other payment credential.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Cancellation and refund terms are set out in our
                <a routerLink="/refund-policy" class="text-accent underline">Cancellation &amp; Refund Policy</a>,
                and delivery of the Services is described in our
                <a routerLink="/service-delivery" class="text-accent underline">Service Delivery Policy</a>.
                Both form part of these Terms of Use.
              </p>
            </div>
          </div>

          <hr class="border-gray-100" />

          <!-- 3. Indemnity -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">3. Indemnity</h2>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              You shall indemnify and hold harmless the Platform Owner, its affiliates and their respective officers, agents and employees from any claim, demand or action, including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, the Privacy Policy or other policies, or your violation of any law, rules or regulations or the rights of a third party, including infringement of intellectual property rights.
            </p>
          </div>

          <hr class="border-gray-100" />

          <!-- 4. Limitation of Liability -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">4. Limitation of Liability</h2>
            <div class="space-y-4">
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                In no event will the Platform Owner be liable for any indirect, consequential, incidental, special or punitive damages, including without limitation damages for loss of profits or revenues, business interruption, loss of business opportunities, loss of data or loss of other economic interests, whether in contract, negligence, tort or otherwise, arising from the use of or inability to use the Services.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                Notwithstanding anything contained in these Terms of Use, the aggregate liability of the Platform Owner, however caused and whether arising in contract, tort, negligence, warranty or otherwise, shall not exceed <strong class="text-navy">the total amount paid by you to us for the Services in the three (3) months immediately preceding the event giving rise to the claim</strong>.
              </p>
            </div>
          </div>

          <hr class="border-gray-100" />

          <!-- 5. Force Majeure -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">5. Force Majeure</h2>
            <p class="text-sm text-gray-600 font-body leading-relaxed">
              The parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
            </p>
          </div>

          <hr class="border-gray-100" />

          <!-- 6. Governing Law and Jurisdiction -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">6. Governing Law and Jurisdiction</h2>
            <div class="space-y-4">
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                These Terms, and any dispute or claim relating to them or their enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts at <strong class="text-navy">Ahmedabad, Gujarat</strong>.
              </p>
              <p class="text-sm text-gray-600 font-body leading-relaxed">
                All concerns or communications relating to these Terms must be communicated to us using the contact information below.
              </p>
            </div>
          </div>

          <hr class="border-gray-100" />

          <!-- 7. Contact -->
          <div>
            <h2 class="text-xl font-display font-bold text-navy mb-4">7. Contact Us</h2>
            <div class="bg-[#F7F8FA] rounded-xl border border-gray-200 p-5 space-y-2">
              <p class="text-sm font-body text-gray-700">
                <span class="font-semibold text-navy">Cosmisk</span> — a sole proprietorship of Sanskar Saxena
              </p>
              <p class="text-sm font-body text-gray-700">Udyam Registration No. UDYAM-GJ-01-0663897</p>
              <p class="text-sm font-body text-gray-700">
                27, Nirmal Bunglows, Nr Karnavati Park, Opp Baroda Expressway,<br />
                CTM, Ahmedabad, Gujarat 380026, India
              </p>
              <p class="text-sm font-body text-gray-700">
                Email:
                <a href="mailto:cosmiskapp&#64;gmail.com" class="text-accent underline">cosmiskapp&#64;gmail.com</a>
              </p>
              <p class="text-sm font-body text-gray-700">Phone: +91 96625 98320</p>
            </div>
            <p class="text-sm text-gray-600 font-body leading-relaxed mt-4">
              For grievances, see our
              <a routerLink="/grievance-officer" class="text-accent underline">Grievance Officer</a> details.
            </p>
          </div>

        </div>
      </div>
    </section>
  `
})
export default class TermsComponent {}
